In [1]:
import torch


In [2]:
# To create a Tensor

example=torch.tensor([
    [[1,2],[1,5]],
    [[4,5],[4,8]],
    [[3,1],[4,7]]
    
])

In [3]:
example

tensor([[[1, 2],
         [1, 5]],

        [[4, 5],
         [4, 8]],

        [[3, 1],
         [4, 7]]])

In [4]:
example.shape

torch.Size([3, 2, 2])

In [5]:
example.device

device(type='cpu')

In [6]:
example.shape[0]

3

In [7]:
example.shape[1]

2

In [8]:
example.size(1)

2

In [9]:
print("shape[0]=",example.shape[0])
print("size of",example.size(1))

shape[0]= 3
size of 2


In [10]:
# To find rank of a tensor - i,e no of dimensions

print("Rank of",len(example.shape))

Rank of 3


In [11]:
# No of elements

print("No of elements in a tensor are",example.numel())

No of elements in a tensor are 12


# indexing Tensor

In [12]:
example

tensor([[[1, 2],
         [1, 5]],

        [[4, 5],
         [4, 8]],

        [[3, 1],
         [4, 7]]])

In [13]:
example[1]

tensor([[4, 5],
        [4, 8]])

In [14]:
example[1,1,0]

tensor(4)

In [15]:
example[2,1,1]

tensor(7)

In [16]:
example_scalar=example[1,1,0]

In [17]:
example_scalar.item()

4

In [18]:
example[:,0,0]

tensor([1, 4, 3])

In [19]:
example[0,:,0]

tensor([1, 1])

## Intiallizing Tensors

In [20]:
# To Create ones in all tensor thaat we have created


In [21]:
torch.ones_like(example)

tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]])

In [22]:
torch.zeros_like(example)

tensor([[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]])

In [23]:
torch.randn_like(example)

RuntimeError: "normal_kernel_cpu" not implemented for 'Long'

In [24]:
torch.randn(2,2,device='cpu')

tensor([[ 1.2787, -0.2295],
        [ 0.6782,  1.1071]])

##  Basic Functions

In [30]:
example=(example -5)*1.5

In [31]:
example.mean()

tensor(-1.8750)

In [32]:
example

tensor([[[-6.0000, -4.5000],
         [-6.0000,  0.0000]],

        [[-1.5000,  0.0000],
         [-1.5000,  4.5000]],

        [[-3.0000, -6.0000],
         [-1.5000,  3.0000]]])

In [33]:
example.std()

tensor(3.4518)

In [35]:
example.mean(1)

tensor([[-6.0000, -2.2500],
        [-1.5000,  2.2500],
        [-2.2500, -1.5000]])

In [36]:
example.mean(0)

tensor([[-3.5000, -3.5000],
        [-3.0000,  2.5000]])

# Python neural network module

In [38]:
import torch.nn as nn
# now beelow this gives no of input layers and output layers
linear=nn.Linear(10,2)
example_input=torch.randn(3,10)
example_output=linear(example_input)
example_output

tensor([[ 0.7100, -0.3349],
        [ 0.5899, -0.2700],
        [-0.5325, -0.3930]], grad_fn=<AddmmBackward>)

# NN.Relu

In [41]:
relu=nn.ReLU()
relu_output=relu(example_output)
print(relu_output)

tensor([[0.7100, 0.0000],
        [0.5899, 0.0000],
        [0.0000, 0.0000]], grad_fn=<ReluBackward0>)


### nn.batch normalization

In [43]:
batchnorm=nn.BatchNorm1d(2)
batchnorm_output=batchnorm(relu_output)
batchnorm_output

tensor([[ 0.8916,  0.0000],
        [ 0.5047,  0.0000],
        [-1.3964,  0.0000]], grad_fn=<NativeBatchNormBackward>)

## nn.Sequential

In [45]:
mlp_layer=nn.Sequential(
nn.Linear(5,2),
nn.BatchNorm1d(2),
nn.ReLU())

test_example=torch.randn(5,5)+1
print("input:")
print(test_example)
print("output:")
print(mlp_layer(test_example))

input:
tensor([[ 2.0849, -0.2803,  1.1291,  0.9106,  0.8718],
        [ 2.1562,  0.6808,  0.8121,  0.0539,  0.9134],
        [ 0.0855,  1.1653, -0.1889,  1.4616,  0.4771],
        [ 1.5701,  2.0963,  0.8440,  1.6150,  1.8692],
        [-0.7729,  1.9937,  1.1079,  0.1623,  1.9599]])
output:
tensor([[0.0000, 0.0363],
        [0.0000, 0.0000],
        [0.6713, 0.6671],
        [0.4585, 1.3141],
        [1.2384, 0.0000]], grad_fn=<ReluBackward0>)


## Optimization

In [47]:
import torch.optim as optim
adam_opt=optim.Adam(mlp_layer.parameters(),lr=1e-1)

## Training Loop

- Set all of the gradients to zero using 'opt.zero_grad()'

In [49]:
train_example=torch.randn(100,5)+1
adam_opt.zero_grad()


curr_loss=torch.abs(1-mlp_layer(train_example)).mean()

curr_loss.backward()
adam_opt.step()
print(curr_loss)

tensor(0.7454, grad_fn=<MeanBackward0>)
